### ISSUE TITLE
Проблемы с расшифровкой строки с байтами

### ISSUE THREAD

**Issue by blohinn** [Sanchez486/egts-python#1]
Привет! У нас есть устройство (ретранслятор), работающий по протоколу EGTS. От него мы получаем данные в формате:

`b'\x01\x00\x00\x0b\x00(\x00\xeb\x01\x01\xd1\x1d\x00\xeb\x01\x01\x82\xd7b\x14\x02\x02\x10\x1a\x00\xbe\xef\xf9\x11\xe6e^\x9a\xe9e\xb2D\x81\x00\x00-\x00\x00\x00\x00\x10l\x00\x00\x00\x00\xcf\xff'`

Есть подозрения, что данные похожи на:
`MSG: (209214768L, 'cguard', '352336080525594', 1564505339, 54.31749, 48.400724, 27, 304, 174, 7, 'CHQ1:93;PKR1:14;NSQ1:17;fuel_base:0;')`

Можешь как-то направить нас в нужное русло? OpenSource community, понятное дело, но можем заплатить. 

Ответь, пожалуйста, здесь или на ivan.blohinn@yandex.ru

**Comment by Sanchez486** [comment]
Привет, не мог ответить, в больнице лежал. Вижу, ты закрыл уже вопрос, если есть актуальные вопросы, готов помочь чем смогу.
